# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 36be1561f367a608870b250e635a818523c5dc182ca9dd1a83fa554cbc089fe3a0636b322a078fba5934fb6e6108c52a968fb0b591f7e148b7a94949c4f45da1

test:
  secret_key_base: d602239992d947d351f01f253c1de6e131c44ff82ef6d2293090e64277f76c84dc8a4613f5441f565e7a3a9c6c3e1a334310f214aa5c4415b017c411218b8ccf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
